-- 2025-10-16 기준 사용자 제공 규제 룰 시드 데이터
-- key: region_key + regulation_area

WITH seed (
  region_key,
  region_1depth,
  region_2depth,
  region_3depth,
  regulation_area
) AS (
  VALUES
    ('서울특별시|강남구', '서울특별시', '강남구', NULL, 'speculative_overheated'),
    ('서울특별시|강남구', '서울특별시', '강남구', NULL, 'adjustment_target'),
    ('서울특별시|서초구', '서울특별시', '서초구', NULL, 'speculative_overheated'),
    ('서울특별시|서초구', '서울특별시', '서초구', NULL, 'adjustment_target'),
    ('서울특별시|송파구', '서울특별시', '송파구', NULL, 'speculative_overheated'),
    ('서울특별시|송파구', '서울특별시', '송파구', NULL, 'adjustment_target'),
    ('서울특별시|용산구', '서울특별시', '용산구', NULL, 'speculative_overheated'),
    ('서울특별시|용산구', '서울특별시', '용산구', NULL, 'adjustment_target'),
    ('서울특별시|강동구', '서울특별시', '강동구', NULL, 'speculative_overheated'),
    ('서울특별시|강동구', '서울특별시', '강동구', NULL, 'adjustment_target'),
    ('서울특별시|강북구', '서울특별시', '강북구', NULL, 'speculative_overheated'),
    ('서울특별시|강북구', '서울특별시', '강북구', NULL, 'adjustment_target'),
    ('서울특별시|강서구', '서울특별시', '강서구', NULL, 'speculative_overheated'),
    ('서울특별시|강서구', '서울특별시', '강서구', NULL, 'adjustment_target'),
    ('서울특별시|관악구', '서울특별시', '관악구', NULL, 'speculative_overheated'),
    ('서울특별시|관악구', '서울특별시', '관악구', NULL, 'adjustment_target'),
    ('서울특별시|광진구', '서울특별시', '광진구', NULL, 'speculative_overheated'),
    ('서울특별시|광진구', '서울특별시', '광진구', NULL, 'adjustment_target'),
    ('서울특별시|구로구', '서울특별시', '구로구', NULL, 'speculative_overheated'),
    ('서울특별시|구로구', '서울특별시', '구로구', NULL, 'adjustment_target'),
    ('서울특별시|금천구', '서울특별시', '금천구', NULL, 'speculative_overheated'),
    ('서울특별시|금천구', '서울특별시', '금천구', NULL, 'adjustment_target'),
    ('서울특별시|노원구', '서울특별시', '노원구', NULL, 'speculative_overheated'),
    ('서울특별시|노원구', '서울특별시', '노원구', NULL, 'adjustment_target'),
    ('서울특별시|도봉구', '서울특별시', '도봉구', NULL, 'speculative_overheated'),
    ('서울특별시|도봉구', '서울특별시', '도봉구', NULL, 'adjustment_target'),
    ('서울특별시|동대문구', '서울특별시', '동대문구', NULL, 'speculative_overheated'),
    ('서울특별시|동대문구', '서울특별시', '동대문구', NULL, 'adjustment_target'),
    ('서울특별시|동작구', '서울특별시', '동작구', NULL, 'speculative_overheated'),
    ('서울특별시|동작구', '서울특별시', '동작구', NULL, 'adjustment_target'),
    ('서울특별시|마포구', '서울특별시', '마포구', NULL, 'speculative_overheated'),
    ('서울특별시|마포구', '서울특별시', '마포구', NULL, 'adjustment_target'),
    ('서울특별시|서대문구', '서울특별시', '서대문구', NULL, 'speculative_overheated'),
    ('서울특별시|서대문구', '서울특별시', '서대문구', NULL, 'adjustment_target'),
    ('서울특별시|성동구', '서울특별시', '성동구', NULL, 'speculative_overheated'),
    ('서울특별시|성동구', '서울특별시', '성동구', NULL, 'adjustment_target'),
    ('서울특별시|성북구', '서울특별시', '성북구', NULL, 'speculative_overheated'),
    ('서울특별시|성북구', '서울특별시', '성북구', NULL, 'adjustment_target'),
    ('서울특별시|양천구', '서울특별시', '양천구', NULL, 'speculative_overheated'),
    ('서울특별시|양천구', '서울특별시', '양천구', NULL, 'adjustment_target'),
    ('서울특별시|영등포구', '서울특별시', '영등포구', NULL, 'speculative_overheated'),
    ('서울특별시|영등포구', '서울특별시', '영등포구', NULL, 'adjustment_target'),
    ('서울특별시|은평구', '서울특별시', '은평구', NULL, 'speculative_overheated'),
    ('서울특별시|은평구', '서울특별시', '은평구', NULL, 'adjustment_target'),
    ('서울특별시|종로구', '서울특별시', '종로구', NULL, 'speculative_overheated'),
    ('서울특별시|종로구', '서울특별시', '종로구', NULL, 'adjustment_target'),
    ('서울특별시|중구', '서울특별시', '중구', NULL, 'speculative_overheated'),
    ('서울특별시|중구', '서울특별시', '중구', NULL, 'adjustment_target'),
    ('서울특별시|중랑구', '서울특별시', '중랑구', NULL, 'speculative_overheated'),
    ('서울특별시|중랑구', '서울특별시', '중랑구', NULL, 'adjustment_target'),
    ('경기도|과천시', '경기도', '과천시', NULL, 'speculative_overheated'),
    ('경기도|과천시', '경기도', '과천시', NULL, 'adjustment_target'),
    ('경기도|광명시', '경기도', '광명시', NULL, 'speculative_overheated'),
    ('경기도|광명시', '경기도', '광명시', NULL, 'adjustment_target'),
    ('경기도|의왕시', '경기도', '의왕시', NULL, 'speculative_overheated'),
    ('경기도|의왕시', '경기도', '의왕시', NULL, 'adjustment_target'),
    ('경기도|하남시', '경기도', '하남시', NULL, 'speculative_overheated'),
    ('경기도|하남시', '경기도', '하남시', NULL, 'adjustment_target')
)
INSERT INTO public.regulation_rules (
  region_key,
  region_1depth,
  region_2depth,
  region_3depth,
  regulation_area,
  transfer_restriction,
  source,
  derived_count,
  is_active,
  effective_from,
  effective_to,
  note,
  updated_at
)
SELECT
  s.region_key,
  s.region_1depth,
  s.region_2depth,
  s.region_3depth,
  s.regulation_area,
  FALSE,
  'manual',
  0,
  TRUE,
  DATE '2025-10-16',
  NULL,
  NULL,
  NOW()
FROM seed s
ON CONFLICT (region_key, regulation_area)
DO UPDATE SET
  region_1depth = EXCLUDED.region_1depth,
  region_2depth = EXCLUDED.region_2depth,
  region_3depth = EXCLUDED.region_3depth,
  transfer_restriction = EXCLUDED.transfer_restriction,
  source = 'manual',
  derived_count = 0,
  is_active = EXCLUDED.is_active,
  effective_from = EXCLUDED.effective_from,
  effective_to = EXCLUDED.effective_to,
  note = EXCLUDED.note,
  updated_at = NOW();
